begin;
select set_config('request.jwt.claim.sub','',true);
select set_config('request.jwt.claims','{}',true);
create temp table poll_test_users(kind text,id uuid default gen_random_uuid());
insert into poll_test_users(kind) values('member'),('other'),('owner');
grant select on poll_test_users to authenticated;
insert into auth.users(id,raw_user_meta_data) select id,jsonb_build_object('nickname','polltest_'||replace(id::text,'-','')) from poll_test_users;
update public.profiles p set status='approved',role=case when t.kind='owner' then 'owner' else 'member' end from poll_test_users t where p.id=t.id;
create temp table poll_test_ids(id bigint);
with p as (insert into public.clan_polls(question,options,is_active,starts_at,created_by) values('Temporary rollback test',array['A','B'],true,now()-interval '1 hour',(select id from poll_test_users where kind='owner')) returning id) insert into poll_test_ids select id from p;
grant select on poll_test_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from poll_test_users where kind='member'),true);
insert into public.clan_poll_votes(poll_id,user_id,option_index) select id,auth.uid(),0 from poll_test_ids;
update public.clan_poll_votes set option_index=1 where poll_id=(select id from poll_test_ids) and user_id=auth.uid();
do $$declare n int; begin
select count(*) into n from public.clan_poll_votes where poll_id=(select id from poll_test_ids) and user_id=auth.uid() and option_index=1;
if n<>1 then raise exception 'Vote replacement failed';end if;
begin update public.clan_poll_votes set option_index=9 where user_id=auth.uid();raise exception 'Invalid accepted';exception when insufficient_privilege or check_violation then null;end;
begin update public.clan_poll_votes set user_id=(select id from poll_test_users where kind='other') where user_id=auth.uid();raise exception 'Transfer accepted';exception when insufficient_privilege then null;end;
delete from public.clan_polls where id=(select id from poll_test_ids);get diagnostics n=row_count;if n<>0 then raise exception 'Member deletion accepted';end if;
end $$;
select set_config('request.jwt.claim.sub',(select id::text from poll_test_users where kind='other'),true);
do $$declare n int;begin update public.clan_poll_votes set option_index=0 where poll_id=(select id from poll_test_ids);get diagnostics n=row_count;if n<>0 then raise exception 'Foreign vote changed';end if;end $$;
reset role;
select set_config('request.jwt.claim.sub','',true);
update public.clan_polls set is_active=false where id=(select id from poll_test_ids);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from poll_test_users where kind='member'),true);
do $$declare n int;begin update public.clan_poll_votes set option_index=0 where poll_id=(select id from poll_test_ids);get diagnostics n=row_count;if n<>0 then raise exception 'Closed vote changed';end if;end $$;
reset role;
select set_config('request.jwt.claim.sub','',true);
update public.clan_polls set is_active=true where id=(select id from poll_test_ids);
update public.profiles set status='blocked' where id=(select id from poll_test_users where kind='member');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from poll_test_users where kind='member'),true);
do $$declare n int;begin update public.clan_poll_votes set option_index=0 where poll_id=(select id from poll_test_ids);get diagnostics n=row_count;if n<>0 then raise exception 'Blocked vote changed';end if;end $$;
select set_config('request.jwt.claim.sub',(select id::text from poll_test_users where kind='owner'),true);
do $$declare n int;begin delete from public.clan_polls where id=(select id from poll_test_ids);get diagnostics n=row_count;if n<>1 then raise exception 'Owner deletion failed';end if;end $$;
reset role;
do $$begin if exists(select 1 from public.clan_poll_votes where poll_id=(select id from poll_test_ids)) then raise exception 'Votes not cascaded';end if;end $$;
rollback;
select 'PASS: replace own vote, invalid/foreign/closed/blocked denied, member delete denied, owner delete cascades. All fixtures rolled back.' as result;
