begin;

create temporary table craft_item_icon_ids (
  item_key text primary key,
  game_item_id integer not null unique
) on commit drop;

insert into craft_item_icon_ids (item_key, game_item_id) values
  ('mat_adamantite_nugget', 1877),
  ('mat_angel_slayer_blade', 6691),
  ('mat_animal_bone', 1872),
  ('mat_animal_skin', 1867),
  ('mat_arcana_mace_head', 6697),
  ('mat_artisans_frame', 1891),
  ('mat_barakiels_axe_piece', 8714),
  ('mat_basalt_battlehammer_head', 6689),
  ('mat_behemoths_tuning_fork_piece', 8715),
  ('mat_blood_tornado_edge', 5539),
  ('mat_bloody_orchid_head', 5536),
  ('mat_braided_hemp', 1878),
  ('mat_branch_of_the_mother_tree_head', 5544),
  ('mat_cabrios_hand_head', 8721),
  ('mat_carnage_bow_stave', 5535),
  ('mat_charcoal', 1871),
  ('mat_coal', 1870),
  ('mat_coarse_bone_powder', 1881),
  ('mat_cokes', 1879),
  ('mat_craftsman_mold', 4047),
  ('mat_daimon_crystal_fragment', 8722),
  ('mat_dark_legions_edge_blade', 5545),
  ('mat_dasparions_staff_edge', 5543),
  ('mat_demon_splinter_blade', 6695),
  ('mat_doom_crusher_head', 8349),
  ('mat_draconic_bow_shaft', 7579),
  ('mat_dragon_grinder_edge', 5538),
  ('mat_dragon_hunter_axe_blade', 6693),
  ('mat_dragon_slayer_edge', 5529),
  ('mat_durable_metal_plate', 5550),
  ('mat_elemental_sword_edge', 5547),
  ('mat_elysian_head', 5533),
  ('mat_enria', 4042),
  ('mat_flaming_dragon_skull_piece', 8342),
  ('mat_forgotten_blade_edge', 6688),
  ('mat_halberd_edge', 5542),
  ('mat_hammer_piece_of_destroyer', 8346),
  ('mat_heavens_divider_edge', 6696),
  ('mat_imperial_staff_head', 6690),
  ('mat_infernal_master_blade', 8331),
  ('mat_iron_ore', 1869),
  ('mat_leather', 1882),
  ('mat_maestro_holder', 4045),
  ('mat_metallic_thread', 5549),
  ('mat_meteor_shower_head', 5532),
  ('mat_mithril_ore', 1876),
  ('mat_mold_glue', 4039),
  ('mat_mold_hardener', 4041),
  ('mat_mold_lubricant', 4040),
  ('mat_naga_storm_piece', 8716),
  ('mat_oriharukon', 1893),
  ('mat_oriharukon_ore', 1874),
  ('mat_saint_spear_blade', 6694),
  ('mat_shyeeds_bow_shaft', 8718),
  ('mat_silver_mold', 1886),
  ('mat_silver_nugget', 1873),
  ('mat_sirras_blade_edge', 8712),
  ('mat_sobekks_hurricane_edge', 8719),
  ('mat_soul_bow_stave', 5534),
  ('mat_soul_separator_head', 5537),
  ('mat_spiritual_eye_piece', 8341),
  ('mat_steel', 1880),
  ('mat_steel_mold', 1883),
  ('mat_stem', 1864),
  ('mat_stone_of_purity', 1875),
  ('mat_suede', 1866),
  ('mat_sword_of_ipos_blade', 8713),
  ('mat_sword_of_miracles_edge', 5546),
  ('mat_tallum_blade_edge', 5548),
  ('mat_tallum_glaive_edge', 5541),
  ('mat_themis_tongue_piece', 8720),
  ('mat_thread', 1868),
  ('mat_tiphons_spear_edge', 8717),
  ('mat_varnish', 1865),
  ('mat_warsmith_holder', 5554),
  ('weapon_a_barakiels_axe', 8680),
  ('weapon_a_behemoths_tuning_fork', 8681),
  ('weapon_a_blood_tornado', 269),
  ('weapon_a_bloody_orchid', 235),
  ('weapon_a_branch_of_the_mother_tree', 213),
  ('weapon_a_cabrios_hand', 8687),
  ('weapon_a_carnage_bow', 288),
  ('weapon_a_daimon_crystal', 8688),
  ('weapon_a_dark_legions_edge', 2500),
  ('weapon_a_dasparions_staff', 212),
  ('weapon_a_destroyer_hammer', 7899),
  ('weapon_a_doom_crusher', 7902),
  ('weapon_a_dragon_grinder', 270),
  ('weapon_a_dragon_slayer', 81),
  ('weapon_a_elemental_sword', 150),
  ('weapon_a_elysian', 164),
  ('weapon_a_flaming_dragon_skull', 7895),
  ('weapon_a_halberd', 98),
  ('weapon_a_infernal_master', 7884),
  ('weapon_a_meteor_shower', 2504),
  ('weapon_a_naga_storm', 8682),
  ('weapon_a_shyeeds_bow', 8684),
  ('weapon_a_sirras_blade', 8678),
  ('weapon_a_sobekks_hurricane', 8685),
  ('weapon_a_soul_bow', 289),
  ('weapon_a_soul_separator', 236),
  ('weapon_a_spiritual_eye', 7894),
  ('weapon_a_sword_of_ipos', 8679),
  ('weapon_a_sword_of_miracles', 151),
  ('weapon_a_tallum_blade', 80),
  ('weapon_a_tallum_glaive', 305),
  ('weapon_a_themis_tongue', 8686),
  ('weapon_a_tiphons_spear', 8683),
  ('weapon_s_angel_slayer', 6367),
  ('weapon_s_arcana_mace', 6579),
  ('weapon_s_basalt_battlehammer', 6365),
  ('weapon_s_demon_splinter', 6371),
  ('weapon_s_draconic_bow', 7575),
  ('weapon_s_dragon_hunter_axe', 6369),
  ('weapon_s_forgotten_blade', 6364),
  ('weapon_s_heavens_divider', 6372),
  ('weapon_s_imperial_staff', 6366),
  ('weapon_s_saint_spear', 6370);

update public.craft_items as item
set game_item_id = null, updated_at = now()
from craft_item_icon_ids as source
where item.item_key = source.item_key
  and item.game_item_id is distinct from source.game_item_id;

update public.craft_items as item
set game_item_id = source.game_item_id, updated_at = now()
from craft_item_icon_ids as source
where item.item_key = source.item_key
  and item.game_item_id is distinct from source.game_item_id;

commit;
