-- Orzeł Biały · Strefa Klanu — deklaracje obecności
create table if not exists public.event_signups (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  response text not null check (response in ('yes','maybe','no')),
  updated_at timestamptz not null default now(),
  unique(event_id,user_id)
);

alter table public.event_signups enable row level security;
grant select, insert, update, delete on table public.event_signups to authenticated;
grant usage, select on sequence public.event_signups_id_seq to authenticated;

-- Zalogowani i zaakceptowani członkowie mogą czytać deklaracje klanu.
drop policy if exists "approved members read signups" on public.event_signups;
create policy "approved members read signups" on public.event_signups
for select to authenticated
using (exists (
  select 1 from public.profiles p
  where p.id = auth.uid() and p.status = 'approved'
));

-- Użytkownik zarządza wyłącznie własną deklaracją.
drop policy if exists "members insert own signup" on public.event_signups;
create policy "members insert own signup" on public.event_signups
for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved')
);

drop policy if exists "members update own signup" on public.event_signups;
create policy "members update own signup" on public.event_signups
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "members delete own signup" on public.event_signups;
create policy "members delete own signup" on public.event_signups
for delete to authenticated
using (user_id = auth.uid());

create index if not exists event_signups_event_idx on public.event_signups(event_id);
create index if not exists event_signups_user_idx on public.event_signups(user_id);
