(async () => {
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  const checks = [];
  const root = document.querySelector('#studio');
  const q = selector => root.querySelector(selector);
  const click = selector => { const button = q(selector); assert(button && !button.disabled, `Unavailable: ${selector}`); button.click(); };
  click('[data-ps-default]');
  click('[data-ps-tab="ornament"]');
  click('[data-ps-field="ornament"][data-ps-value="ice"]');
  click('[data-ps-tab="badges"]');
  click('[data-ps-field="badges"][data-ps-value="pvp"]');
  click('[data-ps-field="badges"][data-ps-value="raid"]');
  if (!q('[data-ps-save]').disabled) click('[data-ps-save]');
  click('[data-ps-tab="badges"]');
  const initial = q('[data-ps-badge-count]').textContent;
  click('[data-ps-field="badges"][data-ps-value="support"]');
  assert(q('[data-ps-badge-count]').textContent === initial, 'Fourth badge was accepted');
  assert(q('[data-ps-message]').textContent.includes('już 3'), 'Missing badge limit feedback');
  click('[data-ps-remove-badge="raid"]');
  click('[data-ps-field="badges"][data-ps-value="support"]');
  assert(q('[data-ps-preview] [aria-label="Wsparcie"]'), 'Chosen badge missing from preview');
  checks.push('badge limit, remove and replace');
  click('[data-ps-tab="background"]');
  click('[data-ps-field="background"][data-ps-value="giran"]');
  assert(q('[data-ps-preview] .ps-cover-giran'), 'Background did not change');
  click('[data-ps-tab="frame"]');
  click('[data-ps-field="frame"][data-ps-value="gold"]');
  assert(q('[data-ps-preview] .ps-frame-gold'), 'Frame did not change');
  click('[data-ps-tab="effects"]');
  click('[data-ps-field="accent"][data-ps-value="violet"]');
  click('[data-ps-field="effect"][data-ps-value="sparks"]');
  const slider = q('[data-ps-intensity]'); slider.value = '80'; slider.dispatchEvent(new Event('input', { bubbles: true }));
  assert(q('[data-ps-preview] [data-effect="sparks"]'), 'Effect did not change');
  assert(q('[data-ps-intensity-output]').textContent === '80%', 'Slider output failed');
  checks.push('background, frame, color, effect and intensity');
  click('[data-ps-cancel]');
  assert(q('[data-ps-preview] [data-ornament="ice"]'), 'Cancel did not restore saved look');
  click('[data-ps-default]');
  assert(q('[data-ps-preview] [data-ornament="none"]'), 'Defaults failed');
  click('[data-ps-random]');
  assert(q('[data-ps-badge-count]').textContent === '3 / 3', 'Random failed');
  checks.push('cancel, defaults and random');
  click('[data-ps-cancel]');
  click('[data-ps-tab="ornament"]');
  return { result: 'PASS', checks };
})();
