import './adminSiteManager.css';
import { SITE_SETTING_FIELDS, applySiteSettings, loadSiteSettings } from './siteSettings.js';

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=[...new Set(SITE_SETTING_FIELDS.map(field=>field.group))];

export function installAdminSiteManager(supabase){
  if(!supabase||window.__obAdminSiteManagerInstalled)return;
  window.__obAdminSiteManagerInstalled=true;
  const wait=()=>{const panel=document.querySelector('#adminSiteContentPanel');if(!panel){setTimeout(wait,120);return}boot(panel)};

  function boot(panel){
    panel.innerHTML=`<div class="site-manager-summary"><div><small>NO-CODE CONTROL CENTER</small><h3>Zarządzanie treścią strony</h3><p>Zmieniasz tutaj teksty i linki. Po zapisaniu są od razu widoczne na stronie.</p></div><span><b>●</b> POŁĄCZONE Z SUPABASE</span></div><div class="site-manager-tabs" role="tablist"><button class="active" type="button" data-site-view="settings">Treści i linki</button><button type="button" data-site-view="announcements">Ogłoszenia</button></div><div id="siteManagerMessage" class="site-manager-message" role="status"></div><section id="siteSettingsView"></section><section id="siteAnnouncementsView" hidden></section>`;
    const message=panel.querySelector('#siteManagerMessage');
    const settingsView=panel.querySelector('#siteSettingsView');
    const announcementsView=panel.querySelector('#siteAnnouncementsView');
    let settings={};let announcements=[];let loaded=false;
    const tell=(text,error=false)=>{message.textContent=text;message.classList.toggle('error',error)};

    const profile=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return null;const {data}=await supabase.from('profiles').select('id,role,status').eq('id',session.user.id).maybeSingle();return data?.role==='owner'&&data?.status==='approved'?data:null};
    const renderSettings=()=>{settingsView.innerHTML=`<form id="adminSiteSettingsForm" class="site-settings-form">${groups.map(group=>`<fieldset><legend>${esc(group)}</legend><div class="site-settings-grid">${SITE_SETTING_FIELDS.filter(field=>field.group===group).map(field=>`<label class="${field.multiline?'wide':''}"><span>${esc(field.label)}</span>${field.multiline?`<textarea data-site-setting="${field.key}" maxlength="${field.max||500}">${esc(settings[field.key]??field.fallback)}</textarea>`:`<input data-site-setting="${field.key}" type="${field.type||'text'}" ${field.max?`maxlength="${field.max}"`:''} value="${esc(settings[field.key]??field.fallback)}">`}</label>`).join('')}</div></fieldset>`).join('')}<div class="site-settings-actions"><button class="secondary-btn" type="button" data-site-reset>Przywróć zapisane</button><button class="primary-btn" type="submit">ZAPISZ I OPUBLIKUJ</button></div></form>`};
    const renderAnnouncements=()=>{announcementsView.innerHTML=`<div class="site-ann-head"><div><h3>Ogłoszenia klanowe</h3><p>Twórz komunikaty widoczne w Strefie Klanu.</p></div><button class="primary-btn" type="button" data-ann-new>+ NOWE OGŁOSZENIE</button></div><div id="siteAnnouncementEditor"></div><div class="site-ann-list">${announcements.length?announcements.map(a=>`<article class="site-ann-row"><div><small>${a.is_pinned?'📌 PRZYPIĘTE':'OGŁOSZENIE'} · ${a.is_active?'WIDOCZNE':'UKRYTE'}</small><h4>${esc(a.title)}</h4><p>${esc(a.body)}</p></div><div><button type="button" data-ann-edit="${a.id}">Edytuj</button><button type="button" data-ann-toggle="${a.id}">${a.is_active?'Ukryj':'Pokaż'}</button><button type="button" data-ann-pin="${a.id}">${a.is_pinned?'Odepnij':'Przypnij'}</button><button class="danger" type="button" data-ann-delete="${a.id}">Usuń</button></div></article>`).join(''):'<div class="site-manager-empty">Brak ogłoszeń. Utwórz pierwszy komunikat dla klanu.</div>'}</div>`};
    const load=async(force=false)=>{if(loaded&&!force)return;const owner=await profile();if(!owner){tell('Ta sekcja jest dostępna wyłącznie dla właściciela strony.',true);return}tell('Pobieranie aktualnych treści…');try{const [current,ann]=await Promise.all([loadSiteSettings(supabase),supabase.from('clan_announcements').select('id,title,body,is_pinned,is_active,created_at,updated_at').order('is_pinned',{ascending:false}).order('created_at',{ascending:false})]);if(ann.error)throw ann.error;settings=current;announcements=ann.data||[];loaded=true;renderSettings();renderAnnouncements();tell('Wszystkie dane są aktualne.')}catch(error){tell(`Nie udało się pobrać treści: ${error.message}`,true)}};
    const announcementForm=(item=null)=>{const host=panel.querySelector('#siteAnnouncementEditor');host.innerHTML=`<form class="site-ann-form"><div><small>${item?'EDYCJA OGŁOSZENIA':'NOWE OGŁOSZENIE'}</small><h4>${item?'Zmień komunikat':'Napisz komunikat dla klanu'}</h4></div><label>Tytuł<input name="title" maxlength="100" required value="${esc(item?.title||'')}"></label><label>Treść<textarea name="body" maxlength="1500" required>${esc(item?.body||'')}</textarea></label><label class="site-check"><input name="pinned" type="checkbox" ${item?.is_pinned?'checked':''}> Przypnij ogłoszenie na górze</label><div><button class="secondary-btn" type="button" data-ann-cancel>Anuluj</button><button class="primary-btn" type="submit">${item?'ZAPISZ ZMIANY':'OPUBLIKUJ'}</button></div></form>`;host.querySelector('[data-ann-cancel]').onclick=()=>host.innerHTML='';host.querySelector('form').onsubmit=async event=>{event.preventDefault();if(!await profile())return;tell('Zapisywanie ogłoszenia…');const form=new FormData(event.currentTarget);const row={title:String(form.get('title')).trim(),body:String(form.get('body')).trim(),is_pinned:form.get('pinned')==='on',updated_at:new Date().toISOString()};const result=item?await supabase.from('clan_announcements').update(row).eq('id',item.id):await supabase.from('clan_announcements').insert({...row,is_active:true});if(result.error){tell(`Błąd zapisu: ${result.error.message}`,true);return}loaded=false;await load(true);tell('✓ Ogłoszenie zostało zapisane.')};};

    panel.querySelector('.site-manager-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-site-view]');if(!button)return;panel.querySelectorAll('[data-site-view]').forEach(x=>x.classList.toggle('active',x===button));settingsView.hidden=button.dataset.siteView!=='settings';announcementsView.hidden=button.dataset.siteView!=='announcements'});
    settingsView.addEventListener('submit',async event=>{if(event.target.id!=='adminSiteSettingsForm')return;event.preventDefault();const owner=await profile();if(!owner)return;tell('Zapisywanie i publikowanie zmian…');const rows=[...event.target.querySelectorAll('[data-site-setting]')].map(input=>({key:input.dataset.siteSetting,value:input.value.trim(),updated_by:owner.id,updated_at:new Date().toISOString()}));const {error}=await supabase.from('site_settings').upsert(rows,{onConflict:'key'});if(error){tell(`Nie udało się zapisać: ${error.message}`,true);return}settings=Object.fromEntries(rows.map(row=>[row.key,row.value]));applySiteSettings(settings);tell('✓ Zapisano. Zmiany są już widoczne na stronie.')});
    settingsView.addEventListener('click',event=>{if(event.target.closest('[data-site-reset]'))renderSettings()});
    announcementsView.addEventListener('click',async event=>{if(event.target.closest('[data-ann-new]')){announcementForm();return}const button=event.target.closest('[data-ann-edit],[data-ann-toggle],[data-ann-pin],[data-ann-delete]');if(!button||!await profile())return;const id=Number(button.dataset.annEdit||button.dataset.annToggle||button.dataset.annPin||button.dataset.annDelete);const item=announcements.find(a=>a.id===id);if(!item)return;if(button.dataset.annEdit){announcementForm(item);return}if(button.dataset.annDelete&&!confirm(`Usunąć ogłoszenie „${item.title}”?`))return;let result;if(button.dataset.annDelete)result=await supabase.from('clan_announcements').delete().eq('id',id);if(button.dataset.annToggle)result=await supabase.from('clan_announcements').update({is_active:!item.is_active,updated_at:new Date().toISOString()}).eq('id',id);if(button.dataset.annPin)result=await supabase.from('clan_announcements').update({is_pinned:!item.is_pinned,updated_at:new Date().toISOString()}).eq('id',id);if(result?.error){tell(`Nie udało się wykonać operacji: ${result.error.message}`,true);return}loaded=false;await load(true);tell('✓ Zmiana została zapisana.')});
    window.addEventListener('orzel:admin-content-open',()=>load(true));
  }
  wait();
}
