const CLASSES=['Dreadnought','Duelist','Phoenix Knight','Hell Knight','Sagittarius','Adventurer','Archmage','Soultaker','Arcana Lord','Cardinal','Hierophant',"Eva's Templar",'Sword Muse','Wind Rider','Moonlight Sentinel','Mystic Muse','Elemental Master',"Eva's Saint",'Shillien Templar','Spectral Dancer','Ghost Hunter','Ghost Sentinel','Storm Screamer','Spectral Master','Shillien Saint','Titan','Grand Khavatari','Dominator','Doomcryer','Fortune Seeker','Maestro'];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=value=>`<option value="">Wybierz klasę</option>${CLASSES.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}`;
const splitBuffs=value=>String(value||'').split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean).slice(0,24);

export function installMemberBuildProfiles(supabase){
  if(!supabase||window.__memberBuildProfilesInstalled)return;
  window.__memberBuildProfilesInstalled=true;
  let user=null,profile=null,loadouts=[],presets=[],community=[];
  const style=document.createElement('style');style.textContent=`
  .build-profile{max-width:980px;margin-top:24px}.build-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:26px 0 10px}.build-head h4{margin:0;color:#e5c67d;font:700 16px Cinzel}.build-head p{margin:4px 0 0;color:#81796d;font-size:10px}.build-btn{border:1px solid #8a6429;background:#2b1d0d;color:#f0ca73;padding:9px 12px;font-size:9px;font-weight:900;cursor:pointer}.build-card{border:1px solid #3d3120;background:#090d0d;padding:14px;margin:9px 0}.build-card-top{display:flex;align-items:center;justify-content:space-between;gap:10px}.build-card-top b{color:#e4d5b5}.build-card-top small{color:#9e7d3e}.build-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:12px}.build-grid label,.buff-editor label{display:grid;gap:5px;color:#a68b55;font-size:8px;font-weight:900}.build-grid input,.build-grid select,.buff-editor input,.buff-editor select,.buff-editor textarea{box-sizing:border-box;width:100%;border:1px solid #41351f;background:#070a0a;color:#eee;padding:9px}.build-card-actions{display:flex;gap:7px;margin-top:11px}.build-card-actions button{border:1px solid #4c3c25;background:#12100b;color:#cdbd9e;padding:7px 10px;font-size:8px;font-weight:900;cursor:pointer}.build-card-actions .danger{color:#dc7b70;border-color:#623630}.buff-editor{display:grid;grid-template-columns:1fr 1fr;gap:9px;border:1px solid #49391f;background:#0b0d0b;padding:14px}.buff-editor .wide{grid-column:1/-1}.buff-editor textarea{min-height:90px;resize:vertical}.buff-slots{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.buff-slots span{border:1px solid #3c3325;background:#11100d;padding:5px 7px;color:#c7bda9;font-size:8px}.buff-slots i{color:#d8ad55;font-style:normal;margin-right:4px}.shared-badge{color:#75cf8a!important}.community-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.build-empty{color:#766f64;font-size:10px;padding:12px 0}.build-message{color:#cdb36e;font-size:9px;margin-left:8px}@media(max-width:700px){.build-grid,.community-grid,.buff-editor{grid-template-columns:1fr}.buff-editor .wide{grid-column:1}.build-head{align-items:flex-start}.build-grid{gap:7px}}
  `;document.head.appendChild(style);
  const host=()=>document.querySelector('[data-zone-panel="profile"]');
  function ensure(){const panel=host();if(!panel||panel.querySelector('#memberBuildProfiles'))return;const root=document.createElement('div');root.id='memberBuildProfiles';root.className='build-profile';root.innerHTML=`<div class="build-head"><div><h4>POSTACIE I SUBCLASSY</h4><p>Dodaj dowolną liczbę subclass. Każda ma osobny sprzęt oraz enchant.</p></div><button class="build-btn" id="addLoadout" type="button">+ DODAJ SUBCLASSĘ</button></div><div id="loadoutList"></div><div class="build-head"><div><h4>MOJE SETUPY BUFFÓW</h4><p>1–24 buffy w kolejności rzucania. Udostępnione presety zobaczą inni członkowie.</p></div></div><form id="buffPresetForm" class="buff-editor"><label>Nazwa setupu<input id="buffPresetTitle" maxlength="80" required placeholder="np. Duelist vs mage"></label><label>Klasa<select id="buffPresetClass">${options('')}</select></label><label class="wide">Buffy — po jednym w linii<textarea id="buffPresetBuffs" required placeholder="Wind Walk\nMight\nHaste\nSong of Warding"></textarea></label><label><span><input id="buffPresetShared" type="checkbox"> Udostępnij innym</span></label><div><button class="build-btn" type="submit">ZAPISZ SETUP</button><span id="buildMessage" class="build-message"></span></div></form><div id="myBuffPresets"></div><div class="build-head"><div><h4>SETUPY SPOŁECZNOŚCI</h4><p>Udostępnione przez innych graczy — możesz skopiować je do edytora.</p></div></div><div id="communityBuffPresets" class="community-grid"></div>`;panel.appendChild(root);bind();render()}
  const equipment=l=>l.equipment||{};
  function renderLoadouts(){const box=document.querySelector('#loadoutList');if(!box)return;box.innerHTML=loadouts.length?loadouts.map((l,i)=>{const e=equipment(l);return `<article class="build-card" data-loadout="${l.id}"><div class="build-card-top"><b>${esc(l.class_name)}</b><small>${l.character_kind==='main'?'GŁÓWNA':'SUBCLASSA #'+(i+1)}</small></div><div class="build-grid"><label>Klasa<select data-field="class_name">${options(l.class_name)}</select></label><label>Nazwa postaci<input data-field="character_name" maxlength="40" value="${esc(l.character_name)}"></label><label>Broń<input data-equipment="weapon" maxlength="80" value="${esc(e.weapon)}"></label><label>Enchant broni<input data-equipment="weaponEnchant" type="number" min="0" max="30" value="${esc(e.weaponEnchant??0)}"></label><label>Set armor<input data-equipment="armor" maxlength="80" value="${esc(e.armor)}"></label><label>Enchant armoru<input data-equipment="armorEnchant" type="number" min="0" max="30" value="${esc(e.armorEnchant??0)}"></label><label>Biżuteria<input data-equipment="jewels" maxlength="120" value="${esc(e.jewels)}"></label><label>Enchant biżu<input data-equipment="jewelsEnchant" type="number" min="0" max="30" value="${esc(e.jewelsEnchant??0)}"></label><label><span><input data-equipment="fullEpic" type="checkbox" ${e.fullEpic?'checked':''}> Full Epic</span></label><label>Augmentacja<input data-equipment="augmentation" maxlength="100" value="${esc(e.augmentation)}"></label></div><div class="build-card-actions"><button data-save-loadout>ZAPISZ</button><button class="danger" data-delete-loadout>USUŃ</button></div></article>`}).join(''):'<p class="build-empty">Nie dodano jeszcze postaci ani subclass.</p>'}
  const presetCard=(p,own)=>`<article class="build-card" data-preset="${p.id}"><div class="build-card-top"><b>${esc(p.title)}</b><small class="${p.is_shared?'shared-badge':''}">${p.is_shared?'UDOSTĘPNIONY':'PRYWATNY'} · ${esc(p.class_name||'dowolna klasa')}</small></div><small>Autor: ${esc(p.author_name)}</small><div class="buff-slots">${(p.buffs||[]).map((b,i)=>`<span><i>${i+1}</i>${esc(b)}</span>`).join('')}</div><div class="build-card-actions"><button data-copy-preset>KOPIUJ DO EDYTORA</button>${own?'<button class="danger" data-delete-preset>USUŃ</button>':''}</div></article>`;
  function render(){renderLoadouts();const mine=document.querySelector('#myBuffPresets'),shared=document.querySelector('#communityBuffPresets');if(mine)mine.innerHTML=presets.length?presets.map(p=>presetCard(p,true)).join(''):'<p class="build-empty">Nie masz jeszcze własnego setupu buffów.</p>';if(shared)shared.innerHTML=community.length?community.map(p=>presetCard(p,false)).join(''):'<p class="build-empty">Nikt jeszcze nie udostępnił setupu.</p>'}
  async function refresh(){if(!user)return;const [l,p,c]=await Promise.all([supabase.from('player_loadouts').select('*').eq('user_id',user.id).order('sort_order'),supabase.from('buff_presets').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}),supabase.from('buff_presets').select('*').eq('is_shared',true).neq('user_id',user.id).order('updated_at',{ascending:false}).limit(30)]);loadouts=l.data||[];presets=p.data||[];community=c.data||[];render()}
  function message(v){const x=document.querySelector('#buildMessage');if(x)x.textContent=v}
  function bind(){const root=document.querySelector('#memberBuildProfiles');root.querySelector('#addLoadout').onclick=async()=>{const row={user_id:user.id,class_name:profile?.character_class||'Duelist',character_kind:loadouts.length?'subclass':'main',sort_order:loadouts.length,equipment:{weapon:'',weaponEnchant:0,armor:'',armorEnchant:0,jewels:'',jewelsEnchant:0,fullEpic:false,augmentation:''}};const {error}=await supabase.from('player_loadouts').insert(row);if(!error)await refresh()};root.onclick=async event=>{const card=event.target.closest('[data-loadout],[data-preset]');if(!card)return;if(event.target.closest('[data-save-loadout]')){const eq={};card.querySelectorAll('[data-equipment]').forEach(x=>eq[x.dataset.equipment]=x.type==='checkbox'?x.checked:x.type==='number'?Number(x.value||0):x.value.trim());const payload={class_name:card.querySelector('[data-field="class_name"]').value,character_name:card.querySelector('[data-field="character_name"]').value.trim(),equipment:eq,updated_at:new Date().toISOString()};if(!payload.class_name)return;await supabase.from('player_loadouts').update(payload).eq('id',card.dataset.loadout);await refresh()}if(event.target.closest('[data-delete-loadout]')){await supabase.from('player_loadouts').delete().eq('id',card.dataset.loadout);await refresh()}if(event.target.closest('[data-delete-preset]')){await supabase.from('buff_presets').delete().eq('id',card.dataset.preset);await refresh()}if(event.target.closest('[data-copy-preset]')){const p=[...presets,...community].find(x=>x.id===card.dataset.preset);if(p){root.querySelector('#buffPresetTitle').value=`Kopia: ${p.title}`.slice(0,80);root.querySelector('#buffPresetClass').value=p.class_name||'';root.querySelector('#buffPresetBuffs').value=(p.buffs||[]).join('\n');root.querySelector('#buffPresetShared').checked=false;root.querySelector('#buffPresetForm').scrollIntoView({behavior:'smooth',block:'center'})}}};root.querySelector('#buffPresetForm').onsubmit=async event=>{event.preventDefault();const buffs=splitBuffs(root.querySelector('#buffPresetBuffs').value);if(!buffs.length){message('Dodaj przynajmniej jeden buff.');return}message('Zapisywanie…');const payload={user_id:user.id,author_name:profile?.nickname||user.email?.split('@')[0]||'Gracz',title:root.querySelector('#buffPresetTitle').value.trim(),class_name:root.querySelector('#buffPresetClass').value,buffs,is_shared:root.querySelector('#buffPresetShared').checked};const {error}=await supabase.from('buff_presets').insert(payload);message(error?'Nie udało się zapisać.':'Setup zapisany.');if(!error){event.target.reset();await refresh()}}}
  async function boot(){const {data}=await supabase.auth.getUser();user=data?.user;if(!user)return;const {data:p}=await supabase.from('profiles').select('nickname,character_class').eq('id',user.id).maybeSingle();profile=p;ensure();await refresh()}
  const observer=new MutationObserver(()=>ensure());observer.observe(document.body,{childList:true,subtree:true});supabase.auth.onAuthStateChange(()=>setTimeout(boot,0));boot();
}
