import { installAdminDashboard } from './adminDashboard.js';

const TECH_DOMAIN = 'members.orzelbialy.local';
const emailForNick = (nick) => `${nick.trim().toLocaleLowerCase().replace(/[^a-z0-9_-]/g, '')}@${TECH_DOMAIN}`;

export function installMemberAuth(supabase) {
  if (!supabase || document.querySelector('#memberAuthLayer')) return;
  installAdminDashboard(supabase);
  const layer = document.createElement('div');
  layer.id = 'memberAuthLayer';
  layer.innerHTML = `<div class="member-auth-box"><button class="member-auth-close" type="button" aria-label="Zamknij">×</button><img src="/images/logo-orzel-bialy.png" alt="Orzeł Biały"><span class="member-kicker">ORZEŁ BIAŁY · ETERNAL X10</span><h2>STREFA KLANU</h2><p class="member-auth-lead">Logowanie i rejestracja członków klanu.</p><div class="member-tabs"><button type="button" data-member-tab="login" class="active">Zaloguj się</button><button type="button" data-member-tab="register">Zarejestruj się</button></div><form id="memberAuthForm" autocomplete="off"><input type="text" name="prevent_autofill_username" autocomplete="username" tabindex="-1" aria-hidden="true" class="auth-autofill-trap"><input type="password" name="prevent_autofill_password" autocomplete="current-password" tabindex="-1" aria-hidden="true" class="auth-autofill-trap"><label>Nick w grze<input id="memberNick" name="clan_nickname" type="text" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="24" required placeholder="np. KiRY"></label><label>Hasło<input id="memberPassword" name="clan_secret" type="password" autocomplete="new-password" minlength="6" required placeholder="Minimum 6 znaków"></label><button class="member-submit" type="submit">ZALOGUJ SIĘ</button><p id="memberAuthFeedback"></p></form></div>`;
  document.body.appendChild(layer);
  const style=document.createElement('style');style.textContent=`#memberAuthLayer{position:fixed;inset:0;z-index:10000;display:none;place-items:center;padding:20px;background:radial-gradient(circle at 50% 20%,#32240ecc,#050708f5 55%);backdrop-filter:blur(8px)}#memberAuthLayer.open{display:grid}.member-auth-box{position:relative;width:min(430px,100%);padding:34px;border:1px solid #8d6a2f;background:linear-gradient(145deg,#101414,#070909);box-shadow:0 30px 80px #000;color:#ddd;text-align:center}.member-auth-box img{width:105px;height:105px;object-fit:contain;filter:drop-shadow(0 0 18px #b9873155)}.member-kicker{display:block;margin-top:8px;color:#c89a49;font:700 10px/1.4 Inter,Arial;letter-spacing:.2em}.member-auth-box h2{margin:8px 0 5px;color:#f0d18b;font:700 28px Georgia,serif}.member-auth-lead{margin:0 0 22px;color:#8f8b82;font-size:13px}.member-auth-close{position:absolute;right:12px;top:10px;border:0;background:none;color:#8e8779;font-size:28px;cursor:pointer}.member-tabs{display:grid;grid-template-columns:1fr 1fr;margin-bottom:20px;border-bottom:1px solid #3b3020}.member-tabs button{padding:11px;border:0;background:none;color:#777;cursor:pointer;font-weight:800}.member-tabs button.active{color:#e2b75f;border-bottom:2px solid #e2b75f}.member-auth-box label{display:block;margin:12px 0;text-align:left;color:#aaa294;font-size:11px;font-weight:800;letter-spacing:.08em}.member-auth-box input{box-sizing:border-box;width:100%;margin-top:7px;padding:13px;border:1px solid #3f382d;background:#0b0e0e;color:#eee;outline:none}.member-auth-box input:focus{border-color:#b88b3e}.auth-autofill-trap{position:absolute!important;left:-9999px!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}.member-submit{width:100%;margin-top:12px;padding:14px;border:1px solid #c99b4d;background:linear-gradient(#3a2a13,#21170c);color:#f2d28c;font-weight:900;cursor:pointer}.member-submit:disabled{opacity:.5}#memberAuthFeedback{min-height:18px;margin:12px 0 0;color:#d6b46d;font-size:12px}.member-auth-entry{margin-left:8px;border:1px solid #8d6a2f!important;color:#e2b75f!important}@media(max-width:650px){.member-auth-box{padding:26px 18px}.member-auth-box img{width:85px;height:85px}}`;document.head.appendChild(style);
  let mode='login';const form=layer.querySelector('#memberAuthForm'),feedback=layer.querySelector('#memberAuthFeedback'),submit=layer.querySelector('.member-submit'),nick=layer.querySelector('#memberNick'),password=layer.querySelector('#memberPassword');
  const clearFields=()=>{nick.value='';password.value='';};
  const setMode=next=>{mode=next;layer.querySelectorAll('[data-member-tab]').forEach(b=>b.classList.toggle('active',b.dataset.memberTab===mode));submit.textContent=mode==='login'?'ZALOGUJ SIĘ':'UTWÓRZ KONTO';password.autocomplete=mode==='login'?'off':'new-password';feedback.textContent='';clearFields();setTimeout(()=>{clearFields();nick.focus();},50);};
  layer.querySelector('.member-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-member-tab]');if(b)setMode(b.dataset.memberTab);});layer.querySelector('.member-auth-close').addEventListener('click',()=>layer.classList.remove('open'));layer.addEventListener('click',e=>{if(e.target===layer)layer.classList.remove('open');});
  form.addEventListener('submit',async e=>{e.preventDefault();const nickname=nick.value.trim(),secret=password.value;if(!/^[A-Za-z0-9_-]{2,24}$/.test(nickname)){feedback.textContent='Nick: 2–24 znaki, litery/cyfry oraz _ lub -.';return;}submit.disabled=true;feedback.textContent='Proszę czekać…';try{if(mode==='register'){const {error}=await supabase.auth.signUp({email:emailForNick(nickname),password:secret,options:{data:{nickname}}});if(error)throw error;await supabase.auth.signOut();feedback.textContent='Konto utworzone. Czeka na akceptację Ownera.';clearFields();}else{const {data,error}=await supabase.auth.signInWithPassword({email:emailForNick(nickname),password:secret});if(error)throw error;const {data:profile,error:profileError}=await supabase.from('profiles').select('nickname,role,status').eq('id',data.user.id).single();if(profileError)throw profileError;if(profile.status==='blocked'){await supabase.auth.signOut();feedback.textContent='To konto jest zablokowane.';}else if(profile.status!=='approved'){await supabase.auth.signOut();feedback.textContent='Konto czeka na akceptację Ownera.';}else{feedback.textContent=`Zalogowano jako ${profile.nickname}.`;setTimeout(()=>layer.classList.remove('open'),650);}}}catch(err){const msg=String(err?.message||'');feedback.textContent=msg.includes('Invalid login')?'Nieprawidłowy nick lub hasło.':msg.includes('already registered')?'Ten nick jest już zajęty.':'Nie udało się wykonać operacji.';}finally{submit.disabled=false;}});
  const entry=document.createElement('button');entry.type='button';entry.className='admin-trigger member-auth-entry';entry.textContent='✦ Strefa klanu';entry.addEventListener('click',()=>{layer.classList.add('open');setMode('login');});const actions=document.querySelector('.header-actions');if(actions)actions.appendChild(entry);
}
