export function installMemberEventSignups(supabase){
 if(!supabase||window.__memberEventSignupsInstalled)return;window.__memberEventSignupsInstalled=true;
 const labels={yes:'BĘDĘ',maybe:'MOŻE',no:'NIE BĘDĘ'};let events=[],mine=new Map(),tableReady=true;
 const css=document.createElement('style');css.textContent=`.zone-signup-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.zone-signup-btn{padding:6px 8px;border:1px solid #584522;background:#0b0f0f;color:#8e887d;font-size:9px;font-weight:900;cursor:pointer}.zone-signup-btn:hover,.zone-signup-btn.active{border-color:#c7973f;color:#f0ca70;background:#2b1e0e}.zone-signup-btn[data-choice="no"].active{border-color:#8c4d42;color:#e18b7d;background:#25110f}.zone-event-row.signup-row{grid-template-columns:72px minmax(130px,1fr) auto}.zone-my-signup{display:grid;grid-template-columns:80px 1fr auto;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid #282218}.zone-choice{padding:5px 8px;border:1px solid #755523;color:#d9aa50;font-size:9px;font-weight:900}.zone-signup-note{margin-top:8px;color:#716c63;font-size:9px}@media(max-width:700px){.zone-event-row.signup-row{grid-template-columns:58px 1fr}.zone-signup-actions{grid-column:1/-1;justify-content:flex-start}}`;document.head.appendChild(css);
 const getUser=async()=>{const {data}=await supabase.auth.getUser();return data?.user||null},key=u=>`ob-event-signups-${u.id}`;
 const readLocal=u=>{try{return new Map(Object.entries(JSON.parse(localStorage.getItem(key(u))||'{}')))}catch{return new Map()}},writeLocal=(u,id,s)=>{const m=readLocal(u);m.set(String(id),s);localStorage.setItem(key(u),JSON.stringify(Object.fromEntries(m)));return m};
 const html=e=>{const d=new Date(`${e.event_date}T${String(e.event_time||'00:00').slice(0,5)}:00`),c=mine.get(String(e.id));return `<div class="zone-event-row signup-row" data-event-id="${e.id}"><div class="zone-event-date">${d.toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit'})}<br>${String(e.event_time||'').slice(0,5)}</div><div class="zone-event-info"><b>${e.name||'Wydarzenie'}</b><small>${e.location||e.boss||'Eternal x10'} · ${e.type||'EVENT'}</small></div><div class="zone-signup-actions">${['yes','maybe','no'].map(x=>`<button class="zone-signup-btn ${c===x?'active':''}" data-choice="${x}">${labels[x]}</button>`).join('')}</div></div>`};
 async function load(){const u=await getUser();if(!u)return;const today=new Date().toISOString().slice(0,10),r=await supabase.from('events').select('id,name,type,boss,event_date,event_time,location').gte('event_date',today).order('event_date').order('event_time').limit(20);events=r.data||[];const s=await supabase.from('event_signups').select('event_id,response').eq('user_id',u.id);if(s.error){tableReady=false;mine=readLocal(u)}else{tableReady=true;mine=new Map((s.data||[]).map(x=>[String(x.event_id),x.response]))}render(u)}
 function render(u){const all=document.querySelector('#memberAllEvents'),up=document.querySelector('#memberUpcomingEvents');if(all)all.innerHTML=events.length?events.map(html).join(''):'<p class="zone-muted">Brak nadchodzących wydarzeń.</p>';if(up)up.innerHTML=events.length?events.slice(0,5).map(html).join(''):'<p class="zone-muted">Brak nadchodzących wydarzeń.</p>';document.querySelectorAll('#memberZoneLayer .zone-signup-btn').forEach(b=>b.onclick=()=>save(u,b.closest('[data-event-id]').dataset.eventId,b.dataset.choice));const p=document.querySelector('[data-zone-panel="signups"]');if(!p)return;let box=p.querySelector('.zone-signups-live');if(!box){p.querySelector('.zone-empty')?.remove();box=document.createElement('div');box.className='zone-signups-live zone-card';p.appendChild(box)}const chosen=events.filter(e=>mine.has(String(e.id)));box.innerHTML=chosen.length?chosen.map(e=>{const d=new Date(`${e.event_date}T${String(e.event_time||'00:00').slice(0,5)}:00`);return `<div class="zone-my-signup"><div class="zone-event-date">${d.toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit'})}<br>${String(e.event_time||'').slice(0,5)}</div><div class="zone-event-info"><b>${e.name}</b><small>${e.type||'EVENT'}</small></div><span class="zone-choice">${labels[mine.get(String(e.id))]}</span></div>`}).join(''):'<p class="zone-muted">Nie masz jeszcze deklaracji. Wejdź w „Wydarzenia” i wybierz Będę / Może / Nie będę.</p>';if(!tableReady)box.innerHTML+='<p class="zone-signup-note">Deklaracje są tymczasowo zapisywane lokalnie na tym urządzeniu.</p>'}
 async function save(u,id,response){if(tableReady){const nickname=u.user_metadata?.nickname||u.email?.split('@')[0]||'Gracz';const r=await supabase.from('event_signups').upsert({event_id:id,user_id:u.id,nickname,response,updated_at:new Date().toISOString()},{onConflict:'event_id,user_id'});if(r.error){tableReady=false;mine=writeLocal(u,id,response)}else mine.set(String(id),response)}else mine=writeLocal(u,id,response);render(u)}
 const obs=new MutationObserver(()=>{if(document.querySelector('#memberZoneLayer.open')){clearTimeout(window.__obSignupLoad);window.__obSignupLoad=setTimeout(load,180)}});obs.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',e=>{if(e.target.closest('[data-zone-view="events"],[data-zone-view="signups"],[data-zone-go="events"],.member-auth-entry.logged-in'))setTimeout(load,220)});setTimeout(load,600);
}
