import './permissionManager.css';
import './permissionOverrides.css';
import { ADMIN_PERMISSIONS, loadAdminPermissionContext } from './adminPermissions.js';

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function installPermissionManager(supabase){
  if(!supabase||window.__obPermissionManagerInstalled)return;
  window.__obPermissionManagerInstalled=true;
  let currentUser=null;let role='admin';let roleRows=[];let overrides=[];
  const modal=document.createElement('div');modal.className='ob-permission-modal';modal.hidden=true;modal.innerHTML=`<section class="ob-permission-window"><header class="ob-permission-head"><div><small>ZARZĄDZANIE DOSTĘPEM</small><h3 id="obPermissionTitle">Uprawnienia</h3></div><button class="ob-permission-close" type="button">×</button></header><div class="ob-permission-body"><div class="ob-permission-role-box"><h4>Domyślne prawa roli</h4><div class="ob-permission-role-select">${['member','leader','admin'].map(item=>`<button type="button" data-permission-role="${item}">${item==='member'?'CZŁONEK':item==='leader'?'LIDER':'ADMINISTRATOR'}</button>`).join('')}</div><div id="obRolePermissionGrid" class="ob-permission-grid"></div><div class="ob-permission-actions"><button class="primary-btn" type="button" data-save-role>ZAPISZ PRAWA ROLI</button></div></div><p id="obPermissionNote" class="ob-permission-note"></p><div id="obUserPermissionGrid" class="ob-permission-grid"></div><div id="obPermissionState" class="ob-permission-state"></div><div class="ob-permission-actions"><button class="secondary-btn" type="button" data-permission-cancel>Anuluj</button><button class="primary-btn" type="button" data-save-user>ZAPISZ DLA UŻYTKOWNIKA</button></div></div></section>`;document.body.append(modal);
  const cards=(rows,prefix)=>{const map=new Map((rows||[]).map(x=>[x.permission,Boolean(x.enabled)]));return ADMIN_PERMISSIONS.map(item=>`<label class="ob-permission-card"><input type="checkbox" data-${prefix}-permission="${item.key}" ${map.get(item.key)?'checked':''}><span><b>${esc(item.label)}</b><span>${esc(item.description)}</span></span></label>`).join('')};
  const state=(text)=>{modal.querySelector('#obPermissionState').textContent=text};
  async function loadRole(nextRole=role){role=nextRole;const {data,error}=await supabase.from('role_permissions').select('permission,enabled').eq('role',role);if(error){state(error.message);return}roleRows=data||[];modal.querySelector('#obRolePermissionGrid').innerHTML=cards(roleRows,'role');modal.querySelectorAll('[data-permission-role]').forEach(b=>b.classList.toggle('active',b.dataset.permissionRole===role))}
  async function open(user){currentUser=user;modal.hidden=false;modal.querySelector('#obPermissionTitle').textContent=`Uprawnienia: ${user.nickname}`;modal.querySelector('#obPermissionNote').textContent=`Ustawienia poniżej dotyczą tylko tej osoby i mają pierwszeństwo przed prawami roli „${user.role}”. Odznaczone pola odbierają dostęp.`;state('Pobieranie uprawnień…');const {data,error}=await supabase.from('user_permission_overrides').select('permission,enabled').eq('user_id',user.id);if(error){state(error.message);return}overrides=data||[];const roleResult=await supabase.from('role_permissions').select('permission,enabled').eq('role',user.role);const roleMap=new Map((roleResult.data||[]).map(x=>[x.permission,Boolean(x.enabled)]));const overrideMap=new Map(overrides.map(x=>[x.permission,Boolean(x.enabled)]));const effective=ADMIN_PERMISSIONS.map(item=>({permission:item.key,enabled:overrideMap.has(item.key)?overrideMap.get(item.key):roleMap.get(item.key)}));modal.querySelector('#obUserPermissionGrid').innerHTML=cards(effective,'user');await loadRole(user.role==='owner'?'admin':user.role);state('')}
  const close=()=>{modal.hidden=true;currentUser=null};modal.querySelector('.ob-permission-close').onclick=close;modal.querySelector('[data-permission-cancel]').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});
  modal.querySelector('.ob-permission-role-select').addEventListener('click',e=>{const b=e.target.closest('[data-permission-role]');if(b)loadRole(b.dataset.permissionRole)});
  modal.querySelector('[data-save-role]').onclick=async()=>{const {data:{session}}=await supabase.auth.getSession();const rows=[...modal.querySelectorAll('[data-role-permission]')].map(input=>({role,permission:input.dataset.rolePermission,enabled:input.checked,updated_by:session.user.id,updated_at:new Date().toISOString()}));state('Zapisywanie praw roli…');const {error}=await supabase.from('role_permissions').upsert(rows,{onConflict:'role,permission'});state(error?`Błąd: ${error.message}`:'✓ Domyślne prawa roli zapisane.')};
  modal.querySelector('[data-save-user]').onclick=async()=>{if(!currentUser)return;const {data:{session}}=await supabase.auth.getSession();const rows=[...modal.querySelectorAll('[data-user-permission]')].map(input=>({user_id:currentUser.id,permission:input.dataset.userPermission,enabled:input.checked,updated_by:session.user.id,updated_at:new Date().toISOString()}));state('Zapisywanie praw użytkownika…');const {error}=await supabase.from('user_permission_overrides').upsert(rows,{onConflict:'user_id,permission'});state(error?`Błąd: ${error.message}`:'✓ Indywidualne uprawnienia zapisane.')};
  const decorate=()=>{document.querySelectorAll('.ob-role-row').forEach(row=>{if(row.querySelector('[data-open-permissions]'))return;const actions=row.querySelector('.ob-role-actions');const roleKey=row.dataset.memberRole;if(!actions||!roleKey||roleKey==='owner')return;const name=row.querySelector('.ob-role-user b')?.textContent||'Użytkownik';const roleButton=actions.querySelector('[data-user-id]');if(!roleButton)return;const button=document.createElement('button');button.type='button';button.className='ob-permission-button';button.dataset.openPermissions=roleButton.dataset.userId;button.dataset.permissionName=name;button.dataset.permissionRole=roleKey;button.textContent='⚙ Uprawnienia';actions.prepend(button)})};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-open-permissions]');if(b){e.preventDefault();e.stopPropagation();open({id:b.dataset.openPermissions,nickname:b.dataset.permissionName,role:b.dataset.permissionRole})}},true);
  new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});decorate();
}
