begin;

create table if not exists public.clan_polls (
  id bigint generated by default as identity primary key,
  question text not null check (char_length(btrim(question)) between 3 and 240),
  description text,
  options text[] not null check (
    cardinality(options) between 2 and 8
    and array_position(options, '') is null
  ),
  is_active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clan_polls_dates_check check (ends_at is null or ends_at > starts_at)
);

create table if not exists public.clan_poll_votes (
  poll_id bigint not null references public.clan_polls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  option_index smallint not null check (option_index >= 0),
  created_at timestamptz not null default now(),
  primary key (poll_id, user_id)
);

create index if not exists clan_polls_active_dates_idx
  on public.clan_polls (is_active, starts_at, ends_at);
create index if not exists clan_poll_votes_poll_id_idx
  on public.clan_poll_votes (poll_id);

alter table public.clan_polls enable row level security;
alter table public.clan_poll_votes enable row level security;

grant select on public.clan_polls to authenticated;
grant insert, update, delete on public.clan_polls to authenticated;
grant usage, select on sequence public.clan_polls_id_seq to authenticated;
grant select on public.clan_poll_votes to authenticated;
grant insert on public.clan_poll_votes to authenticated;

drop policy if exists "clan polls approved members read" on public.clan_polls;
create policy "clan polls approved members read"
  on public.clan_polls
  for select
  to authenticated
  using (
    private.has_admin_permission('manage_content')
    or (
      is_active = true
      and starts_at <= now()
      and (ends_at is null or ends_at > now())
      and exists (
        select 1
        from public.profiles p
        where p.id = (select auth.uid())
          and p.status = 'approved'
          and p.removed_at is null
      )
    )
  );

drop policy if exists "clan polls admins manage" on public.clan_polls;
create policy "clan polls admins manage"
  on public.clan_polls
  for all
  to authenticated
  using (private.has_admin_permission('manage_content'))
  with check (
    private.has_admin_permission('manage_content')
    and (
      created_by is null
      or created_by = (select auth.uid())
    )
  );

drop policy if exists "clan poll votes own or admin read" on public.clan_poll_votes;
create policy "clan poll votes own or admin read"
  on public.clan_poll_votes
  for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or private.has_admin_permission('manage_content')
  );

drop policy if exists "clan poll votes approved members insert" on public.clan_poll_votes;
create policy "clan poll votes approved members insert"
  on public.clan_poll_votes
  for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.status = 'approved'
        and p.removed_at is null
    )
    and exists (
      select 1
      from public.clan_polls p
      where p.id = public.clan_poll_votes.poll_id
        and p.is_active = true
        and p.starts_at <= now()
        and (p.ends_at is null or p.ends_at > now())
        and public.clan_poll_votes.option_index < cardinality(p.options)
    )
  );

create or replace function public.get_clan_poll_results(p_poll_id bigint)
returns table(option_index smallint, vote_count bigint)
language plpgsql
stable
security definer
set search_path = public, private
as $$
begin
  if not (
    private.has_admin_permission('manage_content')
    or exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.status = 'approved'
        and p.removed_at is null
    )
  ) then
    raise exception using errcode = '42501', message = 'Not allowed';
  end if;

  return query
    select v.option_index, count(*)::bigint
    from public.clan_poll_votes v
    where v.poll_id = p_poll_id
    group by v.option_index
    order by v.option_index;
end;
$$;

grant execute on function public.get_clan_poll_results(bigint) to authenticated;

commit;